
ASSERV_BIG = "asserv_big"
ASSERV_MINI = "asserv_mini"

OTHERS_BIG = "others_big"
OTHERS_MINI = "others_mini"

VISIO_BIG = "visio_big"
VISIO_MINI = "visio_mini"

ASSERV_BIG_ENEMY = ASSERV_BIG + "_enemy"
ASSERV_MINI_ENEMY = ASSERV_MINI + "_enemy"

OTHERS_BIG_ENEMY = OTHERS_BIG + "_enemy"
OTHERS_MINI_ENEMY = OTHERS_MINI + "_enemy"

VISIO_BIG_ENEMY = VISIO_BIG + "_enemy"
VISIO_MINI_ENEMY = VISIO_MINI + "_enemy"

HOKUYO = "hokuyo"

FILENAME_MAP = "map.xml"
RAYON_BIGROBOT = 250
RAYON_MINIROBOT = 180
RAYON_ENEMY = 300

LARGEUR_BIGROBOT = 314
LONGUEUR_BIGROBOT = 288
DIST_AXE_TO_BACK = 113

#actionneurs

#pince
PINCE_BAS = 0
PINCE_HAUT = 1
PINCE_MED = 2
