
BLUE = False
RED = True

ASSERV_BIG = "asserv_big"
ASSERV_MINI = "asserv_mini"

OTHERS_BIG = "others_big"
OTHERS_MINI = "others_mini"

VISIO_BIG = "visio_big"
VISIO_MINI = "visio_mini"

ASSERV_BIG_ENEMY = ASSERV_BIG + "_enemy"
ASSERV_MINI_ENEMY = ASSERV_MINI + "_enemy"

OTHERS_BIG_ENEMY = OTHERS_BIG + "_enemy"
OTHERS_MINI_ENEMY = OTHERS_MINI + "_enemy"

VISIO_BIG_ENEMY = VISIO_BIG + "_enemy"
VISIO_MINI_ENEMY = VISIO_MINI + "_enemy"

HOKUYO = "hokuyo"

FILENAME_MAP = "map.xml"
RAYON_BIGROBOT = 155 #normalement 223
RAYON_MINIROBOT = 90
RAYON_ENEMY = 300

LARGEUR_BIGROBOT = 308
LONGUEUR_BIGROBOT = 192
DIST_AXE_TO_BACK = 113

LARGEUR_MINIROBOT = 180
LONGUEUR_MINIROBOT = 102

#actionneurs

#pince
PINCE_BAS = 0
PINCE_HAUT = 1
PINCE_MED = 2
